services:
  db:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    ports:
      - "33006:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  php:
    build: .
    env_file: .env
    volumes:
      - ./:/app
    depends_on:
      - db
